### PR TITLE
Change pycon logo

### PR DESCRIPTION
**Pull request by railsstudent**
Fix issue #41

### CODE REVIEW

**Comment by railsstudent** [comment]
@yookoala @tonyhhyip  Please kindly review. 
I hope I did not miss any logo and icon and stuff

**Comment by railsstudent** [comment]
selection_003
selection_004
selection_005

**Comment by yookoala** [comment]
Do we have a new key visual as well?

I think we should also change the frontpage background and color tone to match the logo. (It is so different from the tone last year.)

**Comment by railsstudent** [comment]
@yookoala Claire updated key visual, I updated pyconhk website this morning.
There are two font colors now: blue and white.  Maybe should stick to one.

**Pull request merged**
