### PR TITLE
Update hkoscon to pycon

### PR DESCRIPTION
**Pull request by railsstudent**
Google Map cannot test locally, need a production to test.

### CODE REVIEW

**Comment by railsstudent** [comment]
screen shot 2017-08-05 at 1 27 18 pm
screen shot 2017-08-05 at 1 27 46 pm


screen shot 2017-08-05 at 1 28 47 pm
screen shot 2017-08-05 at 1 29 08 pm
screen shot 2017-08-05 at 1 34 52 pm
screen shot 2017-08-05 at 1 26 47 pm
screen shot 2017-08-05 at 1 26 57 pm

**Comment by tonyhhyip** [comment]
A bit strange on the "Get Ticket" button

**Comment by railsstudent** [comment]
color or styling?   
Koala changed it in The Loop last Wednesday

**Comment by tonyhhyip** [comment]
Color, Blue with orange background is a bit hard to read, better to change the orange to pink

**Comment by tonyhhyip** [comment]
I refer to the 'Get Ticket' button on top right corner

**Comment by railsstudent** [comment]
@tonyhhyip  @yookoala  Please kindly review. Thanks.

**Comment by tonyhhyip** [comment]
@railsstudent I will take a look during "The LOOP" tonight

**Review by tonyhhyip — DISMISSED** [review]

**Review by tonyhhyip — APPROVED** [review]

**Pull request merged**
